{% set name = "aiormq" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8218dd9f7198d6e7935855468326bbacf0089f926c70baa8dd92944cb2496573

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pamqp ==2.3.0
    - yarl

test:
  imports:
    - aiormq

about:
  home: https://github.com/mosquito/aiormq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: aiormq is a pure python AMQP client library

  description: |
    aiormq is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aiormq
  dev_url: https://github.com/mosquito/aiormq

extra:
  recipe-maintainers:
    - gregfreeman
