{% set name = "aiormq" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dc0fbbc7f8ad5af6a2cc18e00ccc5f925984cde3db6e8fe952c07b7ef157b5f2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pamqp ==2.3.0
    - yarl
    - multidict

test:
  imports:
    - aiormq

about:
  home: https://github.com/mosquito/aiormq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'aiormq is a pure python AMQP client library'

  description: |
    aiormq is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aiormq
  dev_url: https://github.com/mosquito/aiormq

extra:
  recipe-maintainers:
    - gregfreeman
