{% set name = "aiormq" %}
{% set version = "6.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd815d2bb9d8c950361697a74c1b067bc078726c3ef3b837e979a68a4986b148

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pamqp ==3.2.1
    - yarl

test:
  imports:
    - aiormq

about:
  home: https://github.com/mosquito/aiormq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: aiormq is a pure python AMQP client library

  description: |
    aiormq is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aiormq
  dev_url: https://github.com/mosquito/aiormq

extra:
  recipe-maintainers:
    - gregfreeman
    - sphuber
